const PATS = {
  rodilla:  {label:"RODILLA",   labelEn:"KNEE",      color:"#22C55E", icon:"R"},
  empuje:   {label:"EMPUJE",    labelEn:"PUSH",      color:"#2563EB", icon:"E"},
  traccion: {label:"TRACCIÓN",  labelEn:"PULL",      color:"#2563EB", icon:"T"},
  bisagra:  {label:"BISAGRA",   labelEn:"HINGE",     color:"#60A5FA", icon:"B"},
  core:     {label:"CORE",      labelEn:"CORE",      color:"#8B9AB2", icon:"M"},
  movilidad:{label:"MOVILIDAD", labelEn:"MOBILITY",  color:"#22C55E", icon:"M"},
  cardio:   {label:"CARDIO",    labelEn:"CARDIO",    color:"#2563EB", icon:"C"},
  oly:      {label:"OLÍMPICO",  labelEn:"OLYMPIC",   color:"#60A5FA", icon:"O"},
};

const EX = [
  // ── CUADRICEPS ──────────────────────────────────────────────────────
  {id:"sq",     name:"Sentadilla con barra",           nameEn:"Barbell Squat",              pattern:"rodilla", muscle:"Cuadriceps",              equip:"Barra",       youtube:"https://www.youtube.com/watch?v=bEv6CCg2BC8"},
  {id:"gcsq",   name:"Sentadilla de copa",             nameEn:"Goblet Squat",               pattern:"rodilla", muscle:"Cuadriceps",              equip:"Kettlebell",  youtube:"https://www.youtube.com/watch?v=MxsFDhcyFyE"},
  {id:"bsq",    name:"Sentadilla bulgara",             nameEn:"Bulgarian Split Squat",      pattern:"rodilla", muscle:"Cuadriceps",              equip:"Mancuernas",  youtube:"https://www.youtube.com/watch?v=2C-uNgKwPLE"},
  {id:"sumoq",  name:"Sentadilla sumo",                nameEn:"Sumo Squat",                 pattern:"rodilla", muscle:"Cuadriceps/Gluteos",      equip:"Barra",       youtube:"https://www.youtube.com/watch?v=U3HlEF_E9fo"},
  {id:"jsq",    name:"Sentadillas con salto",          nameEn:"Jump Squat",                 pattern:"rodilla", muscle:"Cuadriceps",              equip:"Libre",       youtube:"https://www.youtube.com/watch?v=YGGq0AE5Uyc"},
  {id:"lunge",  name:"Estocadas",                      nameEn:"Lunges",                     pattern:"rodilla", muscle:"Cuadriceps",              equip:"Libre",       youtube:"https://www.youtube.com/watch?v=QOVaHwm-Q6U"},
  {id:"rlunge", name:"Estocadas hacia atras",          nameEn:"Reverse Lunges",             pattern:"rodilla", muscle:"Cuadriceps",              equip:"Libre",       youtube:"https://www.youtube.com/watch?v=xrPteyQLGAo"},
  {id:"llunge", name:"Estocadas laterales",            nameEn:"Lateral Lunges",             pattern:"rodilla", muscle:"Cuadriceps/Abductores",   equip:"Libre",       youtube:"https://www.youtube.com/watch?v=gwWv7aPcD88"},
  {id:"boxup",  name:"Subidas al cajon",               nameEn:"Box Step Up",                pattern:"rodilla", muscle:"Cuadriceps",              equip:"Cajon",       youtube:"https://www.youtube.com/watch?v=dQqApCGd5Ss"},
  {id:"lboxup", name:"Subidas laterales al cajon",     nameEn:"Lateral Box Step Up",        pattern:"rodilla", muscle:"Cuadriceps/Gluteos",      equip:"Cajon",       youtube:"https://www.youtube.com/watch?v=JeB_wGPMqG0"},
  {id:"pistol", name:"Pistols",                        nameEn:"Pistol Squat",               pattern:"rodilla", muscle:"Cuadriceps",              equip:"Libre",       youtube:"https://www.youtube.com/watch?v=vq5-vdgJc0I"},
  {id:"skater", name:"Sentadilla skater",              nameEn:"Skater Squat",               pattern:"rodilla", muscle:"Cuadriceps",              equip:"Libre",       youtube:"https://www.youtube.com/watch?v=d4HQh5RwXoY"},
  {id:"legext", name:"Sillon de cuadriceps",           nameEn:"Leg Extension",              pattern:"rodilla", muscle:"Cuadriceps",              equip:"Maquina",     youtube:"https://www.youtube.com/watch?v=YyvSfVjQeL0"},
  {id:"legext1",name:"Sillon de cuadriceps 1 pierna",  nameEn:"Single Leg Extension",       pattern:"rodilla", muscle:"Cuadriceps",              equip:"Maquina",     youtube:"https://www.youtube.com/watch?v=YyvSfVjQeL0"},
  {id:"lp",     name:"Prensa piernas",                 nameEn:"Leg Press",                  pattern:"rodilla", muscle:"Cuadriceps/Gluteos",      equip:"Maquina",     youtube:"https://www.youtube.com/watch?v=IZxyjW7MPJQ"},
  // ── ISQUIOS / GLUTEOS ────────────────────────────────────────────────
  {id:"dl",     name:"Peso muerto",                    nameEn:"Deadlift",                   pattern:"bisagra", muscle:"Isquios/Gluteos",         equip:"Barra",       youtube:"https://www.youtube.com/watch?v=op9kVnSso6Q"},
  {id:"rdl",    name:"Peso muerto rumano",             nameEn:"Romanian Deadlift",          pattern:"bisagra", muscle:"Isquios/Gluteos",         equip:"Barra",       youtube:"https://www.youtube.com/watch?v=JCXUYuzwNrM"},
  {id:"sldl",   name:"Peso muerto 1 pierna",           nameEn:"Single Leg Deadlift",        pattern:"bisagra", muscle:"Isquios/Gluteos",         equip:"Mancuerna",   youtube:"https://www.youtube.com/watch?v=FIEkFESFOkQ"},
  {id:"sumodl", name:"Peso muerto sumo",               nameEn:"Sumo Deadlift",              pattern:"bisagra", muscle:"Isquios/Gluteos/Abduct",  equip:"Barra",       youtube:"https://www.youtube.com/watch?v=WBPvQMBePGs"},
  {id:"hip",    name:"Hip thrust",                     nameEn:"Hip Thrust",                 pattern:"bisagra", muscle:"Gluteos",                 equip:"Barra",       youtube:"https://www.youtube.com/watch?v=xDmFkJxPzeM"},
  {id:"hip1",   name:"Hip thrust a una pierna",        nameEn:"Single Leg Hip Thrust",      pattern:"bisagra", muscle:"Gluteos",                 equip:"Barra",       youtube:"https://www.youtube.com/watch?v=pq6WHjzOkl8"},
  {id:"kbswing",name:"Swing con KB",                   nameEn:"Kettlebell Swing",           pattern:"bisagra", muscle:"Gluteos/Isquios",         equip:"Kettlebell",  youtube:"https://www.youtube.com/watch?v=YSxHifyI6s8"},
  {id:"nordic", name:"Nordicos",                       nameEn:"Nordic Curl",                pattern:"bisagra", muscle:"Isquios",                 equip:"Libre",       youtube:"https://www.youtube.com/watch?v=d8AAPMBqWFk"},
  {id:"bridge", name:"Puente de gluteos",              nameEn:"Glute Bridge",               pattern:"bisagra", muscle:"Gluteos",                 equip:"Libre",       youtube:"https://www.youtube.com/watch?v=OUgsJ8-Vi0E"},
  {id:"bridge1",name:"Puente de gluteos 1 pierna",     nameEn:"Single Leg Glute Bridge",    pattern:"bisagra", muscle:"Gluteos",                 equip:"Libre",       youtube:"https://www.youtube.com/watch?v=qMKYfZOCNeg"},
  {id:"fbcurl", name:"Curl femoral con fitball",       nameEn:"Fitball Leg Curl",           pattern:"bisagra", muscle:"Isquios",                 equip:"Fitball",     youtube:"https://www.youtube.com/watch?v=Xy97Q3bB3xc"},
  {id:"seathc", name:"Femorales sentado",              nameEn:"Seated Leg Curl",            pattern:"bisagra", muscle:"Isquios",                 equip:"Maquina",     youtube:"https://www.youtube.com/watch?v=1Tq3QdYUuHs"},
  {id:"lc",     name:"Camilla de isquios",             nameEn:"Lying Leg Curl",             pattern:"bisagra", muscle:"Isquios",                 equip:"Maquina",     youtube:"https://www.youtube.com/watch?v=ELOCsoDSmrg"},
  {id:"calf",   name:"Pantorrillas",                   nameEn:"Calf Raise",                 pattern:"bisagra", muscle:"Gemelos",                 equip:"Maquina",     youtube:"https://www.youtube.com/watch?v=-M4-G8p1fCI"},
  // ── EMPUJE ───────────────────────────────────────────────────────────
  {id:"bp",     name:"Press de banca",                 nameEn:"Bench Press",                pattern:"empuje",  muscle:"Pecho",                   equip:"Barra",       youtube:"https://www.youtube.com/watch?v=SCVCLChPQFY"},
  {id:"dbp",    name:"Press de banca con mancuernas",  nameEn:"Dumbbell Bench Press",       pattern:"empuje",  muscle:"Pecho",                   equip:"Mancuernas",  youtube:"https://www.youtube.com/watch?v=QsYre__-aro"},
  {id:"dbp1",   name:"Press de banca mancuerna 1 brazo",nameEn:"Single Arm DB Bench Press", pattern:"empuje",  muscle:"Pecho",                   equip:"Mancuerna",   youtube:"https://www.youtube.com/watch?v=1rHZQPOJMz4"},
  {id:"ibp",    name:"Press inclinado con barra",      nameEn:"Incline Barbell Press",      pattern:"empuje",  muscle:"Pecho alto",              equip:"Barra",       youtube:"https://www.youtube.com/watch?v=DbFgADa2PL8"},
  {id:"idbp",   name:"Press inclinado con mancuernas", nameEn:"Incline Dumbbell Press",     pattern:"empuje",  muscle:"Pecho alto",              equip:"Mancuernas",  youtube:"https://www.youtube.com/watch?v=8iPEnn-ltC8"},
  {id:"ohp",    name:"Press de hombros con barra",     nameEn:"Barbell Overhead Press",     pattern:"empuje",  muscle:"Hombro",                  equip:"Barra",       youtube:"https://www.youtube.com/watch?v=2yjwXTZQDDI"},
  {id:"arnold", name:"Press Arnold",                   nameEn:"Arnold Press",               pattern:"empuje",  muscle:"Hombro",                  equip:"Mancuernas",  youtube:"https://www.youtube.com/watch?v=6Z15_WdXmVw"},
  {id:"mohpm",  name:"Press de hombros en maquina",    nameEn:"Machine Shoulder Press",     pattern:"empuje",  muscle:"Hombro",                  equip:"Maquina",     youtube:"https://www.youtube.com/watch?v=Wqq43dKW1TU"},
  {id:"uohp",   name:"Press hombros unilateral",       nameEn:"Unilateral Shoulder Press",  pattern:"empuje",  muscle:"Hombro",                  equip:"Mancuerna",   youtube:"https://www.youtube.com/watch?v=UMSIITSREt0"},
  {id:"kuohp",  name:"Press hombros unilateral arrodillado",nameEn:"Half Kneeling Press",   pattern:"empuje",  muscle:"Hombro/Core",             equip:"Mancuerna",   youtube:"https://www.youtube.com/watch?v=cKJq3dNNIr4"},
  {id:"land",   name:"Press landmine",                 nameEn:"Landmine Press",             pattern:"empuje",  muscle:"Hombro/Pecho",            equip:"Barra",       youtube:"https://www.youtube.com/watch?v=cayxFfn9SkU"},
  {id:"late",   name:"Vuelos laterales",               nameEn:"Lateral Raise",              pattern:"empuje",  muscle:"Hombro lateral",          equip:"Mancuernas",  youtube:"https://www.youtube.com/watch?v=3VcKaXpzqRo"},
  {id:"ffr",    name:"Vuelos frontales",               nameEn:"Front Raise",                pattern:"empuje",  muscle:"Hombro frontal",          equip:"Mancuernas",  youtube:"https://www.youtube.com/watch?v=sON2s2l-Tks"},
  {id:"tric",   name:"Triceps en polea con soga",      nameEn:"Triceps Rope Pushdown",      pattern:"empuje",  muscle:"Triceps",                 equip:"Polea",       youtube:"https://www.youtube.com/watch?v=vB5OHsJ3EME"},
  {id:"tric2",  name:"Triceps tras nuca en polea",     nameEn:"Overhead Triceps Extension", pattern:"empuje",  muscle:"Triceps",                 equip:"Polea",       youtube:"https://www.youtube.com/watch?v=_gsUck-7M74"},
  {id:"tric3",  name:"Patada de burro en polea",       nameEn:"Cable Kickback",             pattern:"empuje",  muscle:"Triceps",                 equip:"Polea",       youtube:"https://www.youtube.com/watch?v=l3WwE4K2TCA"},
  {id:"tric4",  name:"Triceps tras nuca con soga",     nameEn:"Rope Overhead Extension",    pattern:"empuje",  muscle:"Triceps",                 equip:"Polea",       youtube:"https://www.youtube.com/watch?v=_gsUck-7M74"},
  {id:"tric5",  name:"Triceps frances con mancuernas", nameEn:"French Press",               pattern:"empuje",  muscle:"Triceps",                 equip:"Mancuernas",  youtube:"https://www.youtube.com/watch?v=ir5PsbniVSc"},
  {id:"bankdip",name:"Fondos en banco",                nameEn:"Bench Dip",                  pattern:"empuje",  muscle:"Triceps/Pecho",           equip:"Banco",       youtube:"https://www.youtube.com/watch?v=c3ZGl4pAwZ4"},
  {id:"dip",    name:"Fondos en paralelas",            nameEn:"Parallel Bar Dip",           pattern:"empuje",  muscle:"Pecho/Triceps",           equip:"Paralelas",   youtube:"https://www.youtube.com/watch?v=2z8JmcrW-As"},
  {id:"pushup", name:"Push up",                        nameEn:"Push Up",                    pattern:"empuje",  muscle:"Pecho/Triceps",           equip:"Libre",       youtube:"https://www.youtube.com/watch?v=IODxDxX7oi4"},
  // ── TRACCION ─────────────────────────────────────────────────────────
  {id:"row",    name:"Remo con barra",                 nameEn:"Barbell Row",                pattern:"traccion",muscle:"Espalda",                 equip:"Barra",       youtube:"https://www.youtube.com/watch?v=FWJR5Ve8bnQ"},
  {id:"prow",   name:"Remo pendlay",                   nameEn:"Pendlay Row",                pattern:"traccion",muscle:"Espalda",                 equip:"Barra",       youtube:"https://www.youtube.com/watch?v=RA0Ly0eAaok"},
  {id:"irow",   name:"Remo en banco inclinado",        nameEn:"Incline Dumbbell Row",       pattern:"traccion",muscle:"Espalda",                 equip:"Mancuernas",  youtube:"https://www.youtube.com/watch?v=uiizbEDPFPU"},
  {id:"dbrow",  name:"Remo serrucho",                  nameEn:"Single Arm Dumbbell Row",    pattern:"traccion",muscle:"Espalda",                 equip:"Mancuerna",   youtube:"https://www.youtube.com/watch?v=pYcpY20QaE8"},
  {id:"ringrow",name:"Remo en anillas",                nameEn:"Ring Row",                   pattern:"traccion",muscle:"Espalda",                 equip:"Anillas",     youtube:"https://www.youtube.com/watch?v=LDzSk9MNEo4"},
  {id:"cabrow", name:"Remo bajo en maquina",           nameEn:"Seated Cable Row",           pattern:"traccion",muscle:"Espalda",                 equip:"Maquina",     youtube:"https://www.youtube.com/watch?v=GZbfZ033f74"},
  {id:"uprow",  name:"Remo alto en dorsalera",         nameEn:"High Cable Row",             pattern:"traccion",muscle:"Espalda alta",            equip:"Polea",       youtube:"https://www.youtube.com/watch?v=HKSsG2lhLas"},
  {id:"lat",    name:"Jalon al pecho prono",           nameEn:"Lat Pulldown",               pattern:"traccion",muscle:"Dorsal",                  equip:"Polea",       youtube:"https://www.youtube.com/watch?v=CAwf7n6Luuc"},
  {id:"lats",   name:"Jalon al pecho supino",          nameEn:"Supinated Lat Pulldown",     pattern:"traccion",muscle:"Dorsal",                  equip:"Polea",       youtube:"https://www.youtube.com/watch?v=lueE_MBAhHo"},
  {id:"pu",     name:"Dominadas pronas",               nameEn:"Pull Up",                    pattern:"traccion",muscle:"Dorsal",                  equip:"Barra",       youtube:"https://www.youtube.com/watch?v=eGo4IYlbE5g"},
  {id:"pusu",   name:"Dominadas supinas",              nameEn:"Chin Up",                    pattern:"traccion",muscle:"Dorsal/Biceps",           equip:"Barra",       youtube:"https://www.youtube.com/watch?v=a5-tWfJDUQo"},
  {id:"punu",   name:"Dominadas neutras",              nameEn:"Neutral Grip Pull Up",       pattern:"traccion",muscle:"Dorsal",                  equip:"Barra",       youtube:"https://www.youtube.com/watch?v=rB-KMkRXN4E"},
  {id:"hammer", name:"Remo hammer",                    nameEn:"Hammer Row",                 pattern:"traccion",muscle:"Dorsal/Biceps",           equip:"Mancuernas",  youtube:"https://www.youtube.com/watch?v=vVnXRJLFKyQ"},
  {id:"uproww", name:"Remo al menton con barra W",     nameEn:"Upright Row",                pattern:"traccion",muscle:"Trapecio/Hombro",         equip:"Barra W",     youtube:"https://www.youtube.com/watch?v=Hceg1MfOiJ0"},
  {id:"vertm",  name:"Maquina traccion vertical",      nameEn:"Vertical Traction Machine",  pattern:"traccion",muscle:"Dorsal",                  equip:"Maquina",     youtube:"https://www.youtube.com/watch?v=CAwf7n6Luuc"},
  {id:"pullover",name:"Pull over en polea",            nameEn:"Cable Pullover",             pattern:"traccion",muscle:"Dorsal",                  equip:"Polea",       youtube:"https://www.youtube.com/watch?v=s9SQSGkHiBI"},
  {id:"revfly", name:"Vuelos posteriores sentado",     nameEn:"Reverse Fly",                pattern:"traccion",muscle:"Hombro posterior",        equip:"Mancuernas",  youtube:"https://www.youtube.com/watch?v=TXYnAEDiOX4"},
  {id:"urow",   name:"Remo en polea unilateral",       nameEn:"Single Arm Cable Row",       pattern:"traccion",muscle:"Espalda",                 equip:"Polea",       youtube:"https://www.youtube.com/watch?v=YxJHBaGsXKI"},
  {id:"curl",   name:"Curl de biceps",                 nameEn:"Bicep Curl",                 pattern:"traccion",muscle:"Biceps",                  equip:"Mancuernas",  youtube:"https://www.youtube.com/watch?v=ykJmrZ5v0Oo"},
  {id:"bcurl",  name:"Curl de biceps con barra W",     nameEn:"EZ Bar Curl",                pattern:"traccion",muscle:"Biceps",                  equip:"Barra W",     youtube:"https://www.youtube.com/watch?v=5OtWwT_EWQU"},
  {id:"hcurl",  name:"Biceps martillo",                nameEn:"Hammer Curl",                pattern:"traccion",muscle:"Biceps/Braquial",         equip:"Mancuernas",  youtube:"https://www.youtube.com/watch?v=zC3nLlEvin4"},
  {id:"ccurl",  name:"Biceps concentrado",             nameEn:"Concentration Curl",         pattern:"traccion",muscle:"Biceps",                  equip:"Mancuerna",   youtube:"https://www.youtube.com/watch?v=Jvj2wV0vOFU"},
  {id:"pcurl",  name:"Biceps en polea",                nameEn:"Cable Curl",                 pattern:"traccion",muscle:"Biceps",                  equip:"Polea",       youtube:"https://www.youtube.com/watch?v=V8dZ3pyiCBo"},
  // ── CORE ─────────────────────────────────────────────────────────────
  {id:"plank",  name:"Plancha",                        nameEn:"Plank",                      pattern:"core",    muscle:"Core",                    equip:"Libre",       youtube:"https://www.youtube.com/watch?v=pSHjTRCQxIw"},
  {id:"plankl", name:"Plancha lateral",                nameEn:"Side Plank",                 pattern:"core",    muscle:"Core/Oblicuos",           equip:"Libre",       youtube:"https://www.youtube.com/watch?v=K2VljzCC16g"},
  {id:"ab",     name:"Abdominales",                    nameEn:"Crunches",                   pattern:"core",    muscle:"Core",                    equip:"Libre",       youtube:"https://www.youtube.com/watch?v=Xyd_fa5zoEU"},
  {id:"crunch", name:"Crunch en polea",                nameEn:"Cable Crunch",               pattern:"core",    muscle:"Core",                    equip:"Polea",       youtube:"https://www.youtube.com/watch?v=TSHCc2jJRgQ"},
  {id:"drgflag",name:"Dragon flag",                    nameEn:"Dragon Flag",                pattern:"core",    muscle:"Core",                    equip:"Banco",       youtube:"https://www.youtube.com/watch?v=pvz7k5gO-DE"},
  {id:"hollow", name:"Hollow body",                    nameEn:"Hollow Body Hold",           pattern:"core",    muscle:"Core",                    equip:"Libre",       youtube:"https://www.youtube.com/watch?v=LlDNef_Ztsc"},
  {id:"pallof", name:"Pallof press",                   nameEn:"Pallof Press",               pattern:"core",    muscle:"Core/Oblicuos",           equip:"Polea",       youtube:"https://www.youtube.com/watch?v=AH_QZLm_0-s"},
  {id:"lgrlwk", name:"Farmer walk",                    nameEn:"Farmer Walk",                pattern:"core",    muscle:"Core/Trapecio",           equip:"Mancuernas",  youtube:"https://www.youtube.com/watch?v=Fkzk_RqlYig"},
  {id:"abwheel",name:"Rueda abdominal",                nameEn:"Ab Wheel Rollout",           pattern:"core",    muscle:"Core",                    equip:"Rueda",       youtube:"https://www.youtube.com/watch?v=jhD4Udjk37Y"},
  // ── MOVILIDAD ────────────────────────────────────────────────────────
  {id:"hipflex",name:"Flexibilidad de cadera",         nameEn:"Hip Flexor Stretch",         pattern:"movilidad",muscle:"Cadera",                 equip:"Libre",       youtube:"https://www.youtube.com/watch?v=gRNQDXe0NKY"},
  {id:"t90",    name:"T90",                            nameEn:"90/90 Hip Stretch",          pattern:"movilidad",muscle:"Cadera",                 equip:"Libre",       youtube:"https://www.youtube.com/watch?v=SnMvFQiKOT0"},
  {id:"pigdov", name:"Paloma",                         nameEn:"Pigeon Pose",                pattern:"movilidad",muscle:"Gluteo/Cadera",          equip:"Libre",       youtube:"https://www.youtube.com/watch?v=24Ej7YmBWBQ"},
  {id:"thspin", name:"Rotacion toracica",              nameEn:"Thoracic Rotation",          pattern:"movilidad",muscle:"Columna",                equip:"Libre",       youtube:"https://www.youtube.com/watch?v=GnHVcVMFoLQ"},
  {id:"catrec", name:"Cat camel",                      nameEn:"Cat Camel",                  pattern:"movilidad",muscle:"Columna",                equip:"Libre",       youtube:"https://www.youtube.com/watch?v=kqnua4rHVVA"},
  {id:"shcir",  name:"Circunducciones de hombro",      nameEn:"Shoulder Circles",           pattern:"movilidad",muscle:"Hombro",                 equip:"Libre",       youtube:"https://www.youtube.com/watch?v=4_DGiGb7XoM"},
  {id:"ankmob", name:"Movilidad de tobillo",           nameEn:"Ankle Mobility",             pattern:"movilidad",muscle:"Tobillo",                equip:"Libre",       youtube:"https://www.youtube.com/watch?v=idDnIQFHE7s"},
  {id:"wrstretch",name:"Estiramiento de muneca",       nameEn:"Wrist Stretch",              pattern:"movilidad",muscle:"Muneca",                 equip:"Libre",       youtube:"https://www.youtube.com/watch?v=mSZWSQSSEjE"},
  // ── CARDIO ───────────────────────────────────────────────────────────
  {id:"run",    name:"Trote",                          nameEn:"Jog",                        pattern:"cardio",  muscle:"General",                 equip:"Libre",       youtube:"https://www.youtube.com/watch?v=_kGESn8ArrU"},
  {id:"bike",   name:"Bicicleta",                      nameEn:"Cycling",                    pattern:"cardio",  muscle:"General",                 equip:"Bicicleta",   youtube:"https://www.youtube.com/watch?v=5yjr7tbpOVQ"},
  {id:"row_c",  name:"Remo ergometro",                 nameEn:"Rowing Machine",             pattern:"cardio",  muscle:"General",                 equip:"Remo",        youtube:"https://www.youtube.com/watch?v=H0r_Ql5F4lk"},
  {id:"skip",   name:"Skipping",                       nameEn:"High Knees",                 pattern:"cardio",  muscle:"General",                 equip:"Libre",       youtube:"https://www.youtube.com/watch?v=8opcQdC-V-U"},
  {id:"burpee", name:"Burpees",                        nameEn:"Burpees",                    pattern:"cardio",  muscle:"General",                 equip:"Libre",       youtube:"https://www.youtube.com/watch?v=auBLPXO8Fww"},
  {id:"jump",   name:"Saltos",                         nameEn:"Box Jumps",                  pattern:"cardio",  muscle:"General",                 equip:"Libre",       youtube:"https://www.youtube.com/watch?v=NBY9-kTuHEk"},
  {id:"rope",   name:"Soga",                           nameEn:"Jump Rope",                  pattern:"cardio",  muscle:"General",                 equip:"Soga",        youtube:"https://www.youtube.com/watch?v=FJmRQ5iTXKE"},
  // ── OLIMPICOS ────────────────────────────────────────────────────────
  {id:"snatch", name:"Arranque",                       nameEn:"Snatch",                     pattern:"oly",     muscle:"Cuerpo completo",         equip:"Barra",       youtube:"https://www.youtube.com/watch?v=9xQp2sldyts"},
  {id:"hsnatch",name:"Arranque de colgado",            nameEn:"Hang Snatch",                pattern:"oly",     muscle:"Cuerpo completo",         equip:"Barra",       youtube:"https://www.youtube.com/watch?v=6QKMrArRa7s"},
  {id:"clean",  name:"Cargada",                        nameEn:"Power Clean",                pattern:"oly",     muscle:"Cuerpo completo",         equip:"Barra",       youtube:"https://www.youtube.com/watch?v=KjGvwQl8tis"},
  {id:"cjerk",  name:"Cargada y envion",               nameEn:"Clean and Jerk",             pattern:"oly",     muscle:"Cuerpo completo",         equip:"Barra",       youtube:"https://www.youtube.com/watch?v=6IYzFwHDEik"},
  {id:"ppres",  name:"Push press",                     nameEn:"Push Press",                 pattern:"oly",     muscle:"Hombro/Triceps",          equip:"Barra",       youtube:"https://www.youtube.com/watch?v=X6-DMh-t4nQ"},
  {id:"core_bicho_muerto_disco", name:"Bicho muerto con disco",       nameEn:"Dead Bug with Plate",         pattern:"core", muscle:"Core/Abdomen",   equip:"Disco",      youtube:"https://www.youtube.com/watch?v=9tKE-VKwJDM"},
  {id:"core_twist_ruso_disco",   name:"Twist ruso con disco",          nameEn:"Russian Twist with Plate",    pattern:"core", muscle:"Oblicuos",       equip:"Disco",      youtube:"https://www.youtube.com/watch?v=JyUqwkVpsi8"},
  {id:"core_clam_shell",         name:"Clam shell",                    nameEn:"Clamshell",                   pattern:"core", muscle:"Gluteo medio",   equip:"Colchoneta", youtube:"https://www.youtube.com/watch?v=ZWQMhBVBo8c"},
  {id:"core_abs_paralelas_ext",  name:"Abs en paralelas piernas ext.", nameEn:"Hanging Leg Raise Straight",  pattern:"core", muscle:"Abdomen",        equip:"Paralelas",  youtube:"https://www.youtube.com/watch?v=OXkuOGMDJBA"},
  {id:"core_abs_paralelas_flex", name:"Abs en paralelas piernas flex.",nameEn:"Hanging Knee Raise",          pattern:"core", muscle:"Abdomen",        equip:"Paralelas",  youtube:"https://www.youtube.com/watch?v=XD2_MQULM0E"},
  {id:"core_remo_renegado",      name:"Remo renegado",                 nameEn:"Renegade Row",                pattern:"core", muscle:"Core/Espalda",   equip:"Mancuernas", youtube:"https://www.youtube.com/watch?v=ZWQMhBVBo8c"},
  {id:"core_revolver_olla",      name:"Revolver la olla",              nameEn:"Stir the Pot",                pattern:"core", muscle:"Core",           equip:"Fitball",    youtube:"https://www.youtube.com/watch?v=DHabp9nVFmc"},
  {id:"core_plancha_rkc",        name:"Plancha RKC",                   nameEn:"RKC Plank",                   pattern:"core", muscle:"Core",           equip:"Colchoneta", youtube:"https://www.youtube.com/watch?v=44ScXWFaVBs"},
  {id:"core_plancha_const",      name:"Plancha construcciones",        nameEn:"Plank Build-Ups",             pattern:"core", muscle:"Core",           equip:"Colchoneta", youtube:"https://www.youtube.com/watch?v=DHabp9nVFmc"},
  {id:"core_plancha_3ap",        name:"Plancha 3 apoyos",              nameEn:"3-Point Plank",               pattern:"core", muscle:"Core",           equip:"Colchoneta", youtube:"https://www.youtube.com/watch?v=yeKv5ML5_hU"},
  {id:"core_espinales_colch",    name:"Espinales en colchoneta",       nameEn:"Back Extensions on Mat",      pattern:"core", muscle:"Espinales",      equip:"Colchoneta", youtube:"https://www.youtube.com/watch?v=ph3pMQ6rEp8"},
  {id:"core_espinales_banco45",  name:"Espinales en banco 45",         nameEn:"Back Extensions 45°",         pattern:"core", muscle:"Espinales",      equip:"Banco 45",   youtube:"https://www.youtube.com/watch?v=ph3pMQ6rEp8"},
  {id:"core_espinales_cruzados", name:"Espinales cruzados",            nameEn:"Twisting Back Extensions",   pattern:"core", muscle:"Espinales",      equip:"Banco 45",   youtube:"https://www.youtube.com/watch?v=ph3pMQ6rEp8"},
  {id:"core_bird_dog",           name:"Bird dog",                      nameEn:"Bird Dog",                    pattern:"core", muscle:"Core/Estabilidad",equip:"Colchoneta", youtube:"https://www.youtube.com/watch?v=wiFNA3sqjCA"},
];

const VIDEOS = {
  "sq":    "https://youtu.be/-bJIpOq-LWk",
  "lp":    "https://www.youtube.com/results?search_query=prensa+piernas+tecnica+shorts",
  "lunge": "https://www.youtube.com/results?search_query=zancada+tecnica+tutorial+shorts",
  "dl":    "https://www.youtube.com/results?search_query=peso+muerto+tecnica+tutorial+shorts",
  "rdl":   "https://www.youtube.com/results?search_query=peso+muerto+rumano+tecnica+shorts",
  "hcurl": "https://www.youtube.com/results?search_query=curl+femoral+tecnica+shorts",
  "hip":   "https://www.youtube.com/results?search_query=hip+thrust+tecnica+tutorial+shorts",
  "calf":  "https://www.youtube.com/results?search_query=pantorrillas+gemelos+tecnica+shorts",
  "bp":    "https://www.youtube.com/results?search_query=press+banca+tecnica+tutorial+shorts",
  "ibp":   "https://www.youtube.com/results?search_query=press+inclinado+banca+tecnica+shorts",
  "dbp":   "https://www.youtube.com/results?search_query=press+mancuernas+pecho+tecnica+shorts",
  "fly":   "https://www.youtube.com/results?search_query=aperturas+pecho+mancuernas+tecnica+shorts",
  "ohp":   "https://www.youtube.com/results?search_query=press+militar+hombros+tecnica+shorts",
  "late":  "https://www.youtube.com/results?search_query=elevaciones+laterales+hombro+tecnica+shorts",
  "dip":   "https://www.youtube.com/results?search_query=fondos+paralelas+triceps+tecnica+shorts",
  "tpush": "https://www.youtube.com/results?search_query=extension+triceps+polea+tecnica+shorts",
  "pu":    "https://www.youtube.com/results?search_query=dominadas+tecnica+tutorial+shorts",
  "row":   "https://www.youtube.com/results?search_query=remo+barra+espalda+tecnica+shorts",
  "crow":  "https://www.youtube.com/results?search_query=remo+polea+cable+tecnica+shorts",
  "lat":   "https://www.youtube.com/results?search_query=jalon+pecho+dorsal+tecnica+shorts",
  "facep": "https://www.youtube.com/results?search_query=face+pull+hombro+posterior+tecnica+shorts",
  "curl":  "https://www.youtube.com/results?search_query=curl+biceps+mancuernas+tecnica+shorts",
  "plank": "https://www.youtube.com/results?search_query=plancha+core+tecnica+tutorial+shorts",
  "crunch":"https://www.youtube.com/results?search_query=crunch+abdominal+tecnica+shorts",
  "legr":  "https://www.youtube.com/results?search_query=elevacion+piernas+abdominales+tecnica+shorts",
  "mob1":  "https://www.youtube.com/results?search_query=movilidad+cadera+ejercicios+shorts",
  "mob2":  "https://www.youtube.com/results?search_query=movilidad+toracica+columna+ejercicios+shorts",
  "suppu": "https://www.youtube.com/results?search_query=dominadas+supinas+chin+up+tecnica+shorts",
  "hammer":"https://www.youtube.com/results?search_query=curl+martillo+biceps+tecnica+shorts",
  "legcurl":"https://www.youtube.com/results?search_query=sillon+isquios+curl+femoral+maquina+shorts",
  "legext":"https://www.youtube.com/results?search_query=sillon+cuadriceps+extension+maquina+shorts",
  "trico": "https://www.youtube.com/results?search_query=triceps+polea+pushdown+tecnica+shorts",
  "lateralfly":"https://www.youtube.com/results?search_query=vuelos+laterales+hombro+tecnica+shorts",
  "trot1": "https://www.youtube.com/results?search_query=rotacion+toracica+suelo+movilidad+shorts",
  "trot2": "https://www.youtube.com/results?search_query=rotacion+toracica+cuadrupedia+movilidad+shorts",
  "trot3": "https://www.youtube.com/results?search_query=foam+roller+columna+toracica+movilidad+shorts",
  "trot4": "https://www.youtube.com/results?search_query=rotacion+toracica+banda+elastica+shorts",
  "hipm1": "https://www.youtube.com/results?search_query=90+90+movilidad+cadera+ejercicio+shorts",
  "hipm2": "https://www.youtube.com/results?search_query=apertura+cadera+banda+elastica+movilidad+shorts",
  "hipm3": "https://www.youtube.com/results?search_query=estocada+movilidad+cadera+flexor+shorts",
  "hipm4": "https://www.youtube.com/results?search_query=mariposa+dinamica+aductores+cadera+shorts",
  "shom1": "https://www.youtube.com/results?search_query=rotacion+hombro+banda+manguito+rotador+shorts",
  "shom2": "https://www.youtube.com/results?search_query=dislocaciones+hombro+banda+movilidad+shorts",
  "shom3": "https://www.youtube.com/results?search_query=pass+through+palo+movilidad+hombros+shorts",
  "shom4": "https://www.youtube.com/results?search_query=apertura+pecho+banda+hombros+movilidad+shorts",
  "ankm1": "https://www.youtube.com/results?search_query=movilidad+tobillo+pared+ejercicio+shorts",
  "ankm2": "https://www.youtube.com/results?search_query=movilidad+tobillo+banda+elastica+shorts",
  "ankm3": "https://www.youtube.com/results?search_query=circulos+tobillo+movilidad+shorts",
  "ankm4": "https://www.youtube.com/results?search_query=sentadilla+tobillo+movilidad+shorts",
  "plank2":  "https://www.youtube.com/results?search_query=plancha+lateral+oblicuos+tecnica+shorts",
  "plank3":  "https://www.youtube.com/results?search_query=RKC+plank+tecnica+core+shorts",
  "hollow":  "https://www.youtube.com/results?search_query=hollow+hold+abdominales+tecnica+shorts",
  "abwheel": "https://www.youtube.com/results?search_query=rueda+abdominal+rollout+tecnica+shorts",
  "deadbug": "https://www.youtube.com/results?search_query=dead+bug+core+estabilizacion+shorts",
  "pallof":  "https://www.youtube.com/results?search_query=pallof+press+core+anti+rotacion+shorts",
  "mtnclmb": "https://www.youtube.com/results?search_query=mountain+climber+core+cardio+tecnica+shorts",
  "vup":     "https://www.youtube.com/results?search_query=v+up+abdominales+tecnica+shorts",
  "russtwist":"https://www.youtube.com/results?search_query=russian+twist+oblicuos+tecnica+shorts",
  "situp":   "https://www.youtube.com/results?search_query=sit+up+abdominales+tecnica+shorts",
  "tobar":   "https://www.youtube.com/results?search_query=toes+to+bar+core+tecnica+shorts",
  "woodchop":"https://www.youtube.com/results?search_query=hacha+banda+oblicuos+woodchop+shorts",
  "dragoncurl":"https://www.youtube.com/results?search_query=dragon+flag+core+avanzado+shorts",
  "bgoodmorn":"https://www.youtube.com/results?search_query=buenos+dias+banda+lumbar+core+shorts",
  "curlconc": "https://www.youtube.com/results?search_query=curl+concentrado+biceps+tecnica+shorts",
  "curlpolea":"https://www.youtube.com/results?search_query=curl+biceps+polea+cable+tecnica+shorts",
  "curlw":    "https://www.youtube.com/results?search_query=curl+barra+w+ez+biceps+tecnica+shorts",
  "kickback": "https://www.youtube.com/results?search_query=patada+burro+triceps+mancuerna+tecnica+shorts",
  "rearfly":  "https://www.youtube.com/results?search_query=vuelos+posteriores+banco+hombro+tecnica+shorts",
  "pendlay":  "https://www.youtube.com/results?search_query=remo+pendlay+barra+tecnica+shorts",
  "serrucho": "https://www.youtube.com/results?search_query=remo+serrucho+mancuerna+espalda+tecnica+shorts",
  "remoalto": "https://www.youtube.com/results?search_query=remo+alto+polea+cable+espalda+tecnica+shorts",
};

const IMGS = {
  "sq":    "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/Squats.png/320px-Squats.png",
  "lp":    "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6b/Leg_press.jpg/320px-Leg_press.jpg",
  "lunge": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Lunges.jpg/320px-Lunges.jpg",
  "dl":    "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Deadlift_form.jpg/320px-Deadlift_form.jpg",
  "rdl":   "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Romanian_deadlift.jpg/320px-Romanian_deadlift.jpg",
  "hcurl": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1e/Leg_curl.jpg/320px-Leg_curl.jpg",
  "hip":   "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/Hip_thrust.jpg/320px-Hip_thrust.jpg",
  "calf":  "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c4/Calf_raise.jpg/320px-Calf_raise.jpg",
  "bp":    "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8d/Bench_press_2.jpg/320px-Bench_press_2.jpg",
  "ibp":   "https://upload.wikimedia.org/wikipedia/commons/thumb/2/26/Incline_bench_press.jpg/320px-Incline_bench_press.jpg",
  "dbp":   "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Dumbbell_bench_press.jpg/320px-Dumbbell_bench_press.jpg",
  "fly":   "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/Dumbbell_fly.jpg/320px-Dumbbell_fly.jpg",
  "ohp":   "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Overhead_press.jpg/320px-Overhead_press.jpg",
  "late":  "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Lateral_raise.jpg/320px-Lateral_raise.jpg",
  "dip":   "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Dips_on_a_chair.jpg/320px-Dips_on_a_chair.jpg",
  "tpush": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/Triceps_pushdown.jpg/320px-Triceps_pushdown.jpg",
  "pu":    "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0b/Pull_up_demonstration.jpg/320px-Pull_up_demonstration.jpg",
  "row":   "https://upload.wikimedia.org/wikipedia/commons/thumb/5/52/Bent_over_row.jpg/320px-Bent_over_row.jpg",
  "crow":  "https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/Seated_cable_row.jpg/320px-Seated_cable_row.jpg",
  "lat":   "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Lat_pulldown.jpg/320px-Lat_pulldown.jpg",
  "facep": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Face_pull.jpg/320px-Face_pull.jpg",
  "curl":  "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6c/Dumbbell_curl.jpg/320px-Dumbbell_curl.jpg",
  "plank": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/Plank_position.jpg/320px-Plank_position.jpg",
  "crunch":"https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/Abdominal_crunch.jpg/320px-Abdominal_crunch.jpg",
  "legr":  "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/Leg_raise.jpg/320px-Leg_raise.jpg",
  "mob1":  "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Hip_flexor_stretch.jpg/320px-Hip_flexor_stretch.jpg",
  "mob2":  "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/Thoracic_rotation.jpg/320px-Thoracic_rotation.jpg",
};

export { PATS, EX, VIDEOS, IMGS };
