import React from 'react';
import StudentsSection from '../students/StudentsSection.jsx';

export default function CoachStudentsMain({
  allEx,
  alumnoActivo,
  alumnoProgreso,
  alumnoSesiones,
  alumnos,
  bgCard,
  bgSub,
  border,
  cargarAlumnos,
  cleanActiveCoachAlumnos,
  coachAluBorderSoft,
  coachAluDropdown,
  coachAluDropdownShadow,
  coachAluGhostBtn,
  coachAluShell,
  coachAluSubtle,
  coachAluSurface,
  coachAluTrack,
  coachAlumnosCounts,
  coachAlumnosFilter,
  coachAlumnosListaFiltrada,
  coachAlumnosSearch,
  coachCardMenuId,
  coachDiaSecsOpen,
  coachRoutineDiaIdx,
  coachRutinaMenuOpen,
  completedDays,
  currentWeek,
  darkMode,
  ENTRENADOR_ID,
  es,
  EX,
  generarSugerenciasAlumno,
  getRutinaAsignadaAlumno,
  loadingSB,
  mergeRutinasAsignadas,
  msg,
  newAlumnoData,
  newAlumnoErrors,
  newAlumnoForm,
  notaDiaInput,
  routineForAssign,
  routines,
  rutinasLoaded,
  sb,
  setAddExModal,
  setAddExMuscle,
  setAddExPat,
  setAddExSearch,
  setAddExSelectedIds,
  setAliasModal,
  setAlumnoActivo,
  setAlumnoProgreso,
  setAlumnoSesiones,
  setAlumnos,
  setAssignRoutineId,
  setCoachAlumnosFilter,
  setCoachAlumnosSearch,
  setCoachCardMenuId,
  setChatModal,
  setCoachDiaSecsOpen,
  setCoachDialog,
  setCoachRoutineDiaIdx,
  setCoachRutinaMenuOpen,
  setEditEx,
  setLoadingSB,
  setNewAlumnoData,
  setNewAlumnoErrors,
  setNewAlumnoForm,
  setNotaDiaInput,
  setRegistrosSubTab,
  setRutinasSB,
  setRutinasSBEntrenador,
  sesionesGlobales,
  progresoGlobal,
  showCoachDesktopShell,
  sugsOpen,
  setSugsOpen,
  textMain,
  textMuted,
  toast2,
}) {
  return (
    <StudentsSection
      allEx={allEx}
      alumnoActivo={alumnoActivo}
      alumnoProgreso={alumnoProgreso}
      alumnoSesiones={alumnoSesiones}
      alumnos={alumnos}
      bgCard={bgCard}
      bgSub={bgSub}
      border={border}
      cargarAlumnos={cargarAlumnos}
      cleanActiveCoachAlumnos={cleanActiveCoachAlumnos}
      coachAluBorderSoft={coachAluBorderSoft}
      coachAluDropdown={coachAluDropdown}
      coachAluDropdownShadow={coachAluDropdownShadow}
      coachAluGhostBtn={coachAluGhostBtn}
      coachAluShell={coachAluShell}
      coachAluSubtle={coachAluSubtle}
      coachAluSurface={coachAluSurface}
      coachAluTrack={coachAluTrack}
      coachAlumnosCounts={coachAlumnosCounts}
      coachAlumnosFilter={coachAlumnosFilter}
      coachAlumnosListaFiltrada={coachAlumnosListaFiltrada}
      coachAlumnosSearch={coachAlumnosSearch}
      coachCardMenuId={coachCardMenuId}
      coachDiaSecsOpen={coachDiaSecsOpen}
      coachRoutineDiaIdx={coachRoutineDiaIdx}
      coachRutinaMenuOpen={coachRutinaMenuOpen}
      completedDays={completedDays}
      currentWeek={currentWeek}
      darkMode={darkMode}
      ENTRENADOR_ID={ENTRENADOR_ID}
      es={es}
      EX={EX}
      generarSugerenciasAlumno={generarSugerenciasAlumno}
      getRutinaAsignadaAlumno={getRutinaAsignadaAlumno}
      loadingSB={loadingSB}
      mergeRutinasAsignadas={mergeRutinasAsignadas}
      msg={msg}
      newAlumnoData={newAlumnoData}
      newAlumnoErrors={newAlumnoErrors}
      newAlumnoForm={newAlumnoForm}
      notaDiaInput={notaDiaInput}
      routineForAssign={routineForAssign}
      routines={routines}
      rutinasLoaded={rutinasLoaded}
      sb={sb}
      setAddExModal={setAddExModal}
      setAddExMuscle={setAddExMuscle}
      setAddExPat={setAddExPat}
      setAddExSearch={setAddExSearch}
      setAddExSelectedIds={setAddExSelectedIds}
      setAliasModal={setAliasModal}
      setAlumnoActivo={setAlumnoActivo}
      setAlumnoProgreso={setAlumnoProgreso}
      setAlumnoSesiones={setAlumnoSesiones}
      setAlumnos={setAlumnos}
      setAssignRoutineId={setAssignRoutineId}
      setCoachAlumnosFilter={setCoachAlumnosFilter}
      setCoachAlumnosSearch={setCoachAlumnosSearch}
      setCoachCardMenuId={setCoachCardMenuId}
      setChatModal={setChatModal}
      setCoachDiaSecsOpen={setCoachDiaSecsOpen}
      setCoachDialog={setCoachDialog}
      setCoachRoutineDiaIdx={setCoachRoutineDiaIdx}
      setCoachRutinaMenuOpen={setCoachRutinaMenuOpen}
      setEditEx={setEditEx}
      setLoadingSB={setLoadingSB}
      setNewAlumnoData={setNewAlumnoData}
      setNewAlumnoErrors={setNewAlumnoErrors}
      setNewAlumnoForm={setNewAlumnoForm}
      setNotaDiaInput={setNotaDiaInput}
      setRegistrosSubTab={setRegistrosSubTab}
      setRutinasSB={setRutinasSB}
      setRutinasSBEntrenador={setRutinasSBEntrenador}
      sesionesGlobales={sesionesGlobales}
      progresoGlobal={progresoGlobal}
      showCoachDesktopShell={showCoachDesktopShell}
      sugsOpen={sugsOpen}
      setSugsOpen={setSugsOpen}
      textMain={textMain}
      textMuted={textMuted}
      toast2={toast2}
    />
  );
}
